In [1]:
import pandas as pd
import numpy as np
import os
import glob
from datetime import datetime
import xml.etree.ElementTree as ET 
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
inputt='/kaggle/input/face-mask-detection'
outputt='/kaggle/working'

In [3]:
annotations_dataset='/kaggle/input/face-mask-detection/annotations'
images_dataset='/kaggle/input/face-mask-detection/images'

In [4]:
import os
annot=os.listdir(annotations_dataset)
annotations=[]
for link in annot:
    link2=os.path.join(annotations_dataset,link)
    annotations.append(link2)

In [5]:
csv2=[]
def xmltocsv(param):
    tree=ET.parse(param)
    root=tree.getroot()
    filename=root[1].text
    width=root[2][0].text
    height=root[2][1].text
    depth=root[2][2].text
    segmented=root[3].text
    name=root[4][0].text
    pose=root[4][1].text
    truncated=root[4][2].text
    difficult=root[4][3].text
    xmin=root[4][5][0].text
    ymin=root[4][5][1].text
    xmax=root[4][5][2].text
    ymax=root[4][5][3].text
    hello={
    'file_id':filename,
    'width':width,
    'height':height,
    'depth':depth,
    'segmented':segmented,
    'name':name,
    'pose':pose,
    'truncated':truncated,
    'difficult':difficult,
    'xmin':xmin,
    'xmax':xmax,
    'ymin':ymin,
    'ymax':ymax
    }
    csv2.append(hello)
for i in range(853):
    parame=annotations[i]
    xmltocsv(parame)

In [6]:
cs=pd.DataFrame(csv2)
cs

,file_id,width,height,depth,segmented,name,pose,truncated,difficult,xmin,xmax,ymin,ymax
0,maksssksksss737.png,400,226,3,0,with_mask,Unspecified,0,0,28,46,55,71
1,maksssksksss410.png,400,267,3,0,with_mask,Unspecified,0,0,34,62,153,176
2,maksssksksss537.png,301,400,3,0,without_mask,Unspecified,0,0,95,195,177,295
3,maksssksksss295.png,267,400,3,0,with_mask,Unspecified,0,0,92,168,76,162
4,maksssksksss771.png,400,267,3,0,with_mask,Unspecified,0,0,31,93,109,161
...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,maksssksksss608.png,301,400,3,0,with_mask,Unspecified,0,0,109,218,139,271
849,maksssksksss725.png,301,400,3,0,with_mask,Unspecified,0,0,45,138,215,336
850,maksssksksss13.png,400,226,3,0,with_mask,Unspecified,0,0,28,44,54,71
851,maksssksksss138.png,400,267,3,0,with_mask,Unspecified,0,0,51,128,144,239
852,maksssksksss212.png,267,400,3,0,with_mask,Unspecified,0,0,115,169,75,135

In [7]:
drop=['depth','segmented','pose','truncated','difficult']
csv=cs.drop(drop,axis=1)

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
csv['name']=le.fit_transform(csv['name'])

In [9]:
csv

                 file_id width height  name xmin xmax ymin ymax
0    maksssksksss737.png   400    226     1   28   46   55   71
1    maksssksksss410.png   400    267     1   34   62  153  176
2    maksssksksss537.png   301    400     2   95  195  177  295
3    maksssksksss295.png   267    400     1   92  168   76  162
4    maksssksksss771.png   400    267     1   31   93  109  161
..                   ...   ...    ...   ...  ...  ...  ...  ...
848  maksssksksss608.png   301    400     1  109  218  139  271
849  maksssksksss725.png   301    400     1   45  138  215  336
850   maksssksksss13.png   400    226     1   28   44   54   71
851  maksssksksss138.png   400    267     1   51  128  144  239
852  maksssksksss212.png   267    400     1  115  169   75  135

[853 rows x 8 columns]

In [10]:
cvs=os.listdir(images_dataset)
array=[]
for lisk in cvs:
    lisk1=os.path.join(images_dataset,lisk)
    lisk2=cv2.imread(lisk1)
    array.append(lisk2)

libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

In [11]:
csv['Images']=array

In [12]:
csv

,file_id,width,height,name,xmin,xmax,ymin,ymax,Images
0,maksssksksss737.png,400,226,1,28,46,55,71,"[[[219, 168, 133], [221, 167, 134], [223, 167,..."
1,maksssksksss410.png,400,267,1,34,62,153,176,"[[[87, 126, 157], [87, 126, 157], [87, 127, 15..."
2,maksssksksss537.png,301,400,2,95,195,177,295,"[[[58, 85, 102], [69, 99, 118], [59, 90, 107],..."
3,maksssksksss295.png,267,400,1,92,168,76,162,"[[[171, 162, 167], [174, 165, 170], [177, 168,..."
4,maksssksksss771.png,400,267,1,31,93,109,161,"[[[174, 174, 174], [173, 173, 173], [174, 174,..."
...,...,...,...,...,...,...,...,...,...
848,maksssksksss608.png,301,400,1,109,218,139,271,"[[[185, 127, 90], [187, 124, 91], [189, 126, 9..."
849,maksssksksss725.png,301,400,1,45,138,215,336,"[[[27, 26, 28], [26, 24, 26], [26, 26, 28], [2..."
850,maksssksksss13.png,400,226,1,28,44,54,71,"[[[255, 255, 255], [255, 255, 255], [255, 255,..."
851,maksssksksss138.png,400,267,1,51,128,144,239,"[[[131, 126, 119], [135, 131, 123], [134, 129,..."
852,maksssksksss212.png,267,400,1,115,169,75,135,"[[[44, 38, 31], [45, 39, 31], [49, 42, 35], [5..."

In [13]:
from nltk.tokenize import word_tokenize
z=[]
for i in range(853):
    x=csv.file_id[i]
    y=word_tokenize(x)
    k=[]
    for s in y[0]:
        if s.isdigit():
            k.append(s)
    c=''.join(k)
    z.append(int(c))
    k.pop()
csv['id']=z
csv

,file_id,width,height,name,xmin,xmax,ymin,ymax,Images,id
0,maksssksksss737.png,400,226,1,28,46,55,71,"[[[219, 168, 133], [221, 167, 134], [223, 167,...",737
1,maksssksksss410.png,400,267,1,34,62,153,176,"[[[87, 126, 157], [87, 126, 157], [87, 127, 15...",410
2,maksssksksss537.png,301,400,2,95,195,177,295,"[[[58, 85, 102], [69, 99, 118], [59, 90, 107],...",537
3,maksssksksss295.png,267,400,1,92,168,76,162,"[[[171, 162, 167], [174, 165, 170], [177, 168,...",295
4,maksssksksss771.png,400,267,1,31,93,109,161,"[[[174, 174, 174], [173, 173, 173], [174, 174,...",771
...,...,...,...,...,...,...,...,...,...,...
848,maksssksksss608.png,301,400,1,109,218,139,271,"[[[185, 127, 90], [187, 124, 91], [189, 126, 9...",608
849,maksssksksss725.png,301,400,1,45,138,215,336,"[[[27, 26, 28], [26, 24, 26], [26, 26, 28], [2...",725
850,maksssksksss13.png,400,226,1,28,44,54,71,"[[[255, 255, 255], [255, 255, 255], [255, 255,...",13
851,maksssksksss138.png,400,267,1,51,128,144,239,"[[[131, 126, 119], [135, 131, 123], [134, 129,...",138
852,maksssksksss212.png,267,400,1,115,169,75,135,"[[[44, 38, 31], [45, 39, 31], [49, 42, 35], [5...",212

In [14]:
csvv=csv.drop('file_id',axis=1)

In [15]:
dataset=pd.DataFrame(csvv)

In [16]:
dataset

,width,height,name,xmin,xmax,ymin,ymax,Images,id
0,400,226,1,28,46,55,71,"[[[219, 168, 133], [221, 167, 134], [223, 167,...",737
1,400,267,1,34,62,153,176,"[[[87, 126, 157], [87, 126, 157], [87, 127, 15...",410
2,301,400,2,95,195,177,295,"[[[58, 85, 102], [69, 99, 118], [59, 90, 107],...",537
3,267,400,1,92,168,76,162,"[[[171, 162, 167], [174, 165, 170], [177, 168,...",295
4,400,267,1,31,93,109,161,"[[[174, 174, 174], [173, 173, 173], [174, 174,...",771
...,...,...,...,...,...,...,...,...,...
848,301,400,1,109,218,139,271,"[[[185, 127, 90], [187, 124, 91], [189, 126, 9...",608
849,301,400,1,45,138,215,336,"[[[27, 26, 28], [26, 24, 26], [26, 26, 28], [2...",725
850,400,226,1,28,44,54,71,"[[[255, 255, 255], [255, 255, 255], [255, 255,...",13
851,400,267,1,51,128,144,239,"[[[131, 126, 119], [135, 131, 123], [134, 129,...",138
852,267,400,1,115,169,75,135,"[[[44, 38, 31], [45, 39, 31], [49, 42, 35], [5...",212

In [17]:
tt=['width','height','name','xmin','xmax','ymin','ymax']
for t in tt:
    dataset[t]=dataset[t].astype('int')

In [18]:
dataset['x_center'] = (dataset['xmax']+dataset['xmin'])/(2*640)
dataset['y_center'] = (dataset['ymax']+dataset['ymin'])/(2*480)
dataset['box_height'] = (dataset['xmax']-dataset['xmin'])/(640)
dataset['box_width'] = (dataset['ymax']-dataset['ymin'])/(480)

In [19]:
dataset

,width,height,name,xmin,xmax,ymin,ymax,Images,id,x_center,y_center,box_height,box_width
0,400,226,1,28,46,55,71,"[[[219, 168, 133], [221, 167, 134], [223, 167,...",737,0.057813,0.131250,0.028125,0.033333
1,400,267,1,34,62,153,176,"[[[87, 126, 157], [87, 126, 157], [87, 127, 15...",410,0.075000,0.342708,0.043750,0.047917
2,301,400,2,95,195,177,295,"[[[58, 85, 102], [69, 99, 118], [59, 90, 107],...",537,0.226562,0.491667,0.156250,0.245833
3,267,400,1,92,168,76,162,"[[[171, 162, 167], [174, 165, 170], [177, 168,...",295,0.203125,0.247917,0.118750,0.179167
4,400,267,1,31,93,109,161,"[[[174, 174, 174], [173, 173, 173], [174, 174,...",771,0.096875,0.281250,0.096875,0.108333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,301,400,1,109,218,139,271,"[[[185, 127, 90], [187, 124, 91], [189, 126, 9...",608,0.255469,0.427083,0.170313,0.275000
849,301,400,1,45,138,215,336,"[[[27, 26, 28], [26, 24, 26], [26, 26, 28], [2...",725,0.142969,0.573958,0.145313,0.252083
850,400,226,1,28,44,54,71,"[[[255, 255, 255], [255, 255, 255], [255, 255,...",13,0.056250,0.130208,0.025000,0.035417
851,400,267,1,51,128,144,239,"[[[131, 126, 119], [135, 131, 123], [134, 129,...",138,0.139844,0.398958,0.120313,0.197917
852,267,400,1,115,169,75,135,"[[[44, 38, 31], [45, 39, 31], [49, 42, 35], [5...",212,0.221875,0.218750,0.084375,0.125000

In [20]:
Train=dataset[0:700]
Test=dataset[700:853]

In [21]:
csv

,file_id,width,height,name,xmin,xmax,ymin,ymax,Images,id
0,maksssksksss737.png,400,226,1,28,46,55,71,"[[[219, 168, 133], [221, 167, 134], [223, 167,...",737
1,maksssksksss410.png,400,267,1,34,62,153,176,"[[[87, 126, 157], [87, 126, 157], [87, 127, 15...",410
2,maksssksksss537.png,301,400,2,95,195,177,295,"[[[58, 85, 102], [69, 99, 118], [59, 90, 107],...",537
3,maksssksksss295.png,267,400,1,92,168,76,162,"[[[171, 162, 167], [174, 165, 170], [177, 168,...",295
4,maksssksksss771.png,400,267,1,31,93,109,161,"[[[174, 174, 174], [173, 173, 173], [174, 174,...",771
...,...,...,...,...,...,...,...,...,...,...
848,maksssksksss608.png,301,400,1,109,218,139,271,"[[[185, 127, 90], [187, 124, 91], [189, 126, 9...",608
849,maksssksksss725.png,301,400,1,45,138,215,336,"[[[27, 26, 28], [26, 24, 26], [26, 26, 28], [2...",725
850,maksssksksss13.png,400,226,1,28,44,54,71,"[[[255, 255, 255], [255, 255, 255], [255, 255,...",13
851,maksssksksss138.png,400,267,1,51,128,144,239,"[[[131, 126, 119], [135, 131, 123], [134, 129,...",138
852,maksssksksss212.png,267,400,1,115,169,75,135,"[[[44, 38, 31], [45, 39, 31], [49, 42, 35], [5...",212

In [22]:
tt=['width','height','name','xmin','xmax','ymin','ymax']
for t in tt:
    csv[t]=csv[t].astype('int')

In [23]:
csv['x_center'] = (csv['xmax']+csv['xmin'])/(2*640)
csv['y_center'] = (csv['ymax']+csv['ymin'])/(2*480)
csv['box_height'] = (csv['xmax']-csv['xmin'])/(640)
csv['box_width'] = (csv['ymax']-csv['ymin'])/(480)

In [24]:
csv

,file_id,width,height,name,xmin,xmax,ymin,ymax,Images,id,x_center,y_center,box_height,box_width
0,maksssksksss737.png,400,226,1,28,46,55,71,"[[[219, 168, 133], [221, 167, 134], [223, 167,...",737,0.057813,0.131250,0.028125,0.033333
1,maksssksksss410.png,400,267,1,34,62,153,176,"[[[87, 126, 157], [87, 126, 157], [87, 127, 15...",410,0.075000,0.342708,0.043750,0.047917
2,maksssksksss537.png,301,400,2,95,195,177,295,"[[[58, 85, 102], [69, 99, 118], [59, 90, 107],...",537,0.226562,0.491667,0.156250,0.245833
3,maksssksksss295.png,267,400,1,92,168,76,162,"[[[171, 162, 167], [174, 165, 170], [177, 168,...",295,0.203125,0.247917,0.118750,0.179167
4,maksssksksss771.png,400,267,1,31,93,109,161,"[[[174, 174, 174], [173, 173, 173], [174, 174,...",771,0.096875,0.281250,0.096875,0.108333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,maksssksksss608.png,301,400,1,109,218,139,271,"[[[185, 127, 90], [187, 124, 91], [189, 126, 9...",608,0.255469,0.427083,0.170313,0.275000
849,maksssksksss725.png,301,400,1,45,138,215,336,"[[[27, 26, 28], [26, 24, 26], [26, 26, 28], [2...",725,0.142969,0.573958,0.145313,0.252083
850,maksssksksss13.png,400,226,1,28,44,54,71,"[[[255, 255, 255], [255, 255, 255], [255, 255,...",13,0.056250,0.130208,0.025000,0.035417
851,maksssksksss138.png,400,267,1,51,128,144,239,"[[[131, 126, 119], [135, 131, 123], [134, 129,...",138,0.139844,0.398958,0.120313,0.197917
852,maksssksksss212.png,267,400,1,115,169,75,135,"[[[44, 38, 31], [45, 39, 31], [49, 42, 35], [5...",212,0.221875,0.218750,0.084375,0.125000

In [25]:
drop=['width','height','xmin','xmax','ymin','ymax','id','Images']
main=csv.drop(drop,axis=1)

In [26]:
main

                 file_id  name  x_center  y_center  box_height  box_width
0    maksssksksss737.png     1  0.057813  0.131250    0.028125   0.033333
1    maksssksksss410.png     1  0.075000  0.342708    0.043750   0.047917
2    maksssksksss537.png     2  0.226562  0.491667    0.156250   0.245833
3    maksssksksss295.png     1  0.203125  0.247917    0.118750   0.179167
4    maksssksksss771.png     1  0.096875  0.281250    0.096875   0.108333
..                   ...   ...       ...       ...         ...        ...
848  maksssksksss608.png     1  0.255469  0.427083    0.170313   0.275000
849  maksssksksss725.png     1  0.142969  0.573958    0.145313   0.252083
850   maksssksksss13.png     1  0.056250  0.130208    0.025000   0.035417
851  maksssksksss138.png     1  0.139844  0.398958    0.120313   0.197917
852  maksssksksss212.png     1  0.221875  0.218750    0.084375   0.125000

[853 rows x 6 columns]